Convert unit tests to googletest
bigladder/HPWHsim pull request #200
Opened 2024-02-05 16:49 UTC by spahrenk

2024-02-07 19:34 UTC, nealkruis commented
@spahrenk this looks good to me. A lot of unrelated cleanup here too that should maybe be in a separate branch, but it's not worth the effort to separate it out now. The source file in the companion CSE branch been completely reformatted, making it impossible to see where the API has caused changes. This highlights the need to get clang formatting set up in CSE, but for now, can you change the branch with your "autoformat" turned off?

2024-02-12 17:17 UTC, spahrenk commented
Ah, OK. I'll clean that up.

2024-02-26 16:14 UTC, nealkruis requested changes

2024-02-26 16:14 UTC, nealkruis commented on CMakeLists.txt
> +    add_subdirectory(test/unit_tests)
One very minor change here: This subdirectory should be added from the test/CMakeLists.txt.

2024-02-26 17:32 UTC, nealkruis approved these changes

2024-02-26 17:32 UTC, merged